name: r-daily

on:
  schedule:
     - cron: 0 0 * * *
  push:
    branches:
      - r-daily

jobs:
  r-daily-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build development environment
        run: |
          nix-build r-daily.nix

      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "noreply@email.com"

      - name: Synching fork
        run: |
          git remote add upstream https://github.com/nixos/nixpkgs
          git checkout r-daily
          git fetch upstream
          git reset --hard upstream/master

      - name: Update R packages
        run: |
          nix-shell r-daily.nix --run "Rscript -e pkgs/development/r-modules/generate-r-packages.R cran > pkgs/development/r-modules/cran-packages.nix.new"
          mv cran-packages.nix.new cran-packages.nix

          nix-shell r-daily.nix --run "Rscript -e pkgs/development/r-modules/generate-r-packages.R bioc > pkgs/development/r-modules/bioc-packages.nix.new"
          mv bioc-packages.nix.new bioc-packages.nix

          nix-shell r-daily.nix --run "Rscript -e pkgs/development/r-modules/generate-r-packages.R bioc-annotation > pkgs/development/r-modules/bioc-annotation-packages.nix.new"
          mv bioc-annotation-packages.nix.new bioc-annotation-packages.nix

          nix-shell r-daily.nix --run "Rscript -e pkgs/development/r-modules/generate-r-packages.R bioc-experiment > pkgs/development/r-modules/bioc-experiment-packages.nix.new"
          mv bioc-experiment-packages.nix.new bioc-experiment-packages.nix

      - name: Pushing updates
        run: |
          git add .
          git commit -m "daily update"
          git push --force origin r-daily
